# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab156261302fbdcf7e76d68c194417085c18e6ec85f2188fc45682ad0c2facaf8ab2a074e1b5b706e8ffcbab60542d01ba9554d049b9de4b599251fd5fe7ffc3

test:
  secret_key_base: 5e18acf3120931d4e17e9df017aa3e8bdc43c26c427ec70a962a39e6ded39171fc53ee6e15f0d9ba511192a26c917e25736c8ceab47b06476ff7c2e422fdfd4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
